---
name: 'devcontainer'
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Login to ghcr.io
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install just
        run: sudo snap install --edge --classic just

      - name: Build container
        run: just devcontainer-build

      - name: Push to ghcr.io
        if: github.ref == 'refs/heads/main'
        run: just devcontainer-push